name: Build GSI

on:
  workflow_dispatch:

env:
  DISABLE_RUNNER_CLEANUP: false # should ONLY be set to true if ABSOLUTELY necessary
  ROM_NAME: VoltageOS
  ROM_VERSION: 3.2

jobs:
  build-gsi:
    runs-on: [self-hosted]
    steps:
    - name: setup git config
      run: |
        git config --global user.email "androidbuild@localhost"
        git config --global user.name "androidbuild"
    - name: checkout basic repo
      uses: actions/checkout@v4
    - name: clone rom manifest
      run: repo init -u https://github.com/VoltageOS/manifest.git -b 14 --depth=1
    - name: copy manifest config
      run: |
        mkdir -p .repo/local_manifests
        cp -v manifest.xml .repo/local_manifests/
    - name: setup git-lfs hook
      run: git lfs install
    - name: perform full sources sync (with auto retry)
      uses: nick-fields/retry@v3
      with:
        command: repo sync -c -j8 --force-sync --no-clone-bundle --no-tags # set to 8 cores to slow down sync and avoid github-actions timeouts
        max_attempts: 3
        retry_on: error
        timeout_minutes: 20
    - name: fetch all git-lfs objects
      run: |
        grep -l 'merge=lfs' $( find $PWD -name .gitattributes ) /dev/null | while IFS= read -r line; do
          dir=$(dirname $line)
          echo $dir
          ( cd $dir ; git lfs pull )
        done
    - name: apply patches
      run: |
        ./patches/apply.sh . trebledroid
        ./patches/apply.sh . personal
    - name: generate base rom config
      run: |
        cp -v ../../../Voltage.mk .
        bash generate.sh Voltage
      working-directory: device/phh/treble
    - name: build treble app
      run: |
        . build/envsetup.sh
        cd treble_app/
        bash build.sh release
        cp -v TrebleApp.apk ../vendor/hardware_overlay/TrebleApp/app.apk
    - name: build standard gapps arm64 image
      run: |
        . build/envsetup.sh
        lunch treble_arm64_bgN-userdebug
        make systemimage -j"$(nproc --all)"
        mv -v out/target/product/tdgsi_arm64_ab/system.img out/target/product/tdgsi_arm64_ab/system_gapps.img
    - name: run vndk sepolicy tests (as early as possible)
      run: |
        . build/envsetup.sh
        lunch treble_arm64_bgN-userdebug
        make vndk-test-sepolicy -j"$(nproc --all)"
    - name: build standard vanilla arm64 image
      run: |
        . build/envsetup.sh
        lunch treble_arm64_bvN-userdebug
        make systemimage -j"$(nproc --all)"
        mv -v out/target/product/tdgsi_arm64_ab/system.img out/target/product/tdgsi_arm64_ab/system_vanilla.img
    - name: build standard gapps arm32_binder64 image
      run: |
        . build/envsetup.sh
        lunch treble_a64_bgN-userdebug
        make systemimage -j"$(nproc --all)"
        mv -v out/target/product/tdgsi_a64_ab/system.img out/target/product/tdgsi_a64_ab/system_gapps.img
    - name: build standard vanilla arm32_binder64 image
      run: |
        . build/envsetup.sh
        lunch treble_a64_bvN-userdebug
        make systemimage -j"$(nproc --all)"
        mv -v out/target/product/tdgsi_a64_ab/system.img out/target/product/tdgsi_a64_ab/system_vanilla.img
    - name: adapt vndklite gapps arm64 image
      run: |
        cp -v ../out/target/product/tdgsi_arm64_ab/system_gapps.img standard_system_gapps_arm64.img
        sudo bash lite-adapter.sh 64 standard_system_gapps_arm64.img
        sudo mv s.img s_arm64_gapps.img
        sudo chown $(whoami):$(id | awk -F'[()]' '{ print $2 }') s_arm64_gapps.img
      working-directory: treble_adapter
    - name: adapt vndklite vanilla arm64 image
      run: |
        cp -v ../out/target/product/tdgsi_arm64_ab/system_vanilla.img standard_system_vanilla_arm64.img
        sudo bash lite-adapter.sh 64 standard_system_vanilla_arm64.img
        sudo mv s.img s_arm64_vanilla.img
        sudo chown $(whoami):$(id | awk -F'[()]' '{ print $2 }') s_arm64_vanilla.img
      working-directory: treble_adapter
    - name: adapt vndklite gapps arm32_binder64 image
      run: |
        cp -v ../out/target/product/tdgsi_a64_ab/system_gapps.img standard_system_gapps_arm32_binder64.img
        sudo bash lite-adapter.sh 32 standard_system_gapps_arm32_binder64.img
        sudo mv s.img s_arm32_binder64_gapps.img
        sudo chown $(whoami):$(id | awk -F'[()]' '{ print $2 }') s_arm32_binder64_gapps.img
      working-directory: treble_adapter
    - name: adapt vndklite vanilla arm32_binder64 image
      run: |
        cp -v ../out/target/product/tdgsi_a64_ab/system_vanilla.img standard_system_vanilla_arm32_binder64.img
        sudo bash lite-adapter.sh 32 standard_system_vanilla_arm32_binder64.img
        sudo mv s.img s_arm32_binder64_vanilla.img
        sudo chown $(whoami):$(id | awk -F'[()]' '{ print $2 }') s_arm32_binder64_vanilla.img
      working-directory: treble_adapter
    - name: rename image files
      run: |
        buildDate=$(date +%Y%m%d)
        cp -v out/target/product/tdgsi_arm64_ab/system_gapps.img "${ROM_NAME}"-gapps-arm64-ab-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v out/target/product/tdgsi_arm64_ab/system_vanilla.img "${ROM_NAME}"-vanilla-arm64-ab-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v out/target/product/tdgsi_a64_ab/system_gapps.img "${ROM_NAME}"-gapps-arm32_binder64-ab-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v out/target/product/tdgsi_a64_ab/system_vanilla.img "${ROM_NAME}"-vanilla-arm32_binder64-ab-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v treble_adapter/s_arm64_gapps.img "${ROM_NAME}"-gapps-arm64-ab-vndklite-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v treble_adapter/s_arm64_vanilla.img "${ROM_NAME}"-vanilla-arm64-ab-vndklite-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v treble_adapter/s_arm32_binder64_gapps.img "${ROM_NAME}"-gapps-arm32_binder64-ab-vndklite-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
        cp -v treble_adapter/s_arm32_binder64_vanilla.img "${ROM_NAME}"-vanilla-arm32_binder64-ab-vndklite-"${ROM_VERSION}"-"${buildDate}"-UNOFFICIAL.img
    - name: compress all images with xz
      run: find . -maxdepth 1 -name '*.img' -exec xz -9 -T0 -v -z "{}" \;
    - name: upload gapps arm64 standard image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-gapps-arm64-ab-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload vanilla arm64 standard image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-vanilla-arm64-ab-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload gapps arm64 vndklite image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-gapps-arm64-ab-vndklite-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload vanilla arm64 vndklite image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-vanilla-arm64-ab-vndklite-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload gapps arm32_binder64 standard image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-gapps-arm32_binder64-ab-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload vanilla arm32_binder64 standard image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-vanilla-arm32_binder64-ab-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload gapps arm32_binder64 vndklite image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-gapps-arm32_binder64-ab-vndklite-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: upload vanilla arm32_binder64 vndklite image to temp.sh
      run: find . -maxdepth 1 -name "${ROM_NAME}-vanilla-arm32_binder64-ab-vndklite-${ROM_VERSION}-*-UNOFFICIAL.img.xz" -exec curl -F "file=@{}" https://temp.sh/upload \;
    - name: cleanup work directory
      uses: eviden-actions/clean-self-hosted-runner@v1
      if: ${{ always() }} # Run even if previous steps in the job fail or are canceled
