name: Build VoltageOS GSI
on:
  workflow_dispatch:

env:
  CCACHE_COMPRESS: 1
  CCACHE_MAXSIZE: 50G
  USE_CCACHE: 1

jobs:
  build-voltage:
    runs-on: [self-hosted]
    steps:
    - name: clone voltage manifest
      run: repo init -u https://github.com/VoltageOS/manifest.git -b 14 --depth=1
    - name: copy manifest config
      run: |
        mkdir -p .repo/local_manifests
        cp -v manifest.xml .repo/local_manifests/
    - name: setup git-lfs hook
      run: git lfs install
    - name: perform full sources sync
      run: repo sync -c -j"$(nproc --all)" --force-sync --no-clone-bundle --no-tags
    - name: apply patches
      run: |
        ./patches/apply.sh . trebledroid
        ./patches/apply.sh . ponces
        ./patches/apply.sh . personal
        ./patches/apply.sh . graphene
    - name: generate base voltage config
      run: bash generate.sh Voltage
      working-directory: device/phh/treble
    - name: initialize ccache
      run: ccache -M 50G -F 0
    - name: build gsi
      run: |
        . build/envsetup.sh
        lunch treble_arm64_bvN-userdebug
        make systemimage -j"$(nproc --all)"
